#ifndef TASK_TYPES_H
#define TASK_TYPES_H

// Forward declarations
class CTask;

//////////////////////////////////////////////////////////////////////////
// CTaskTypes
//////////////////////////////////////////////////////////////////////////

namespace CTaskTypes
{
    enum eTaskType
    {
        TASK_INVALID_ID = -1,

// For now all tasks that have a script dependency go at the top, so adding new tasks doesn't
// change their ordering and cause asserts
        TASK_HANDS_UP = 0,
        TASK_CLIMB_LADDER = 1,
        TASK_EXIT_VEHICLE = 2,
        TASK_COMBAT_ROLL = 3,
        TASK_AIM_GUN_ON_FOOT = 4,

//player tasks
        TASK_MOVE_PLAYER,
        TASK_PLAYER_ON_FOOT,
        TASK_PLAYER_ON_HORSE,
        TASK_WEAPON,
        TASK_PLAYER_WEAPON,
        TASK_PLAYER_IDLES,

//Network Player Settings Task
        TASK_COMPLEX_NETWORK_PLAYER_SETTINGS_TASKS,

//basic tasks
        TASK_NONE,
        TASK_UNINTERRUPTABLE,
        TASK_PAUSE,
        TASK_DO_NOTHING,
        TASK_GET_UP,
        TASK_GET_UP_AND_STAND_STILL,
        TASK_FALL_OVER,
        TASK_FALL_AND_GET_UP,
        TASK_CRAWL,
        TASK_COMPLEX_FALL_AND_STAY_DOWN,
        TASK_SIT_IDLE,
        TASK_SIT_DOWN,
        TASK_HIT_RESPONSE,
        TASK_COMPLEX_ON_FIRE,
        TASK_DAMAGE_ELECTRIC,
        TASK_STEP_UP,
        TASK_TRIGGER_LOOK_AT,
        TASK_CLEAR_LOOK_AT,
        TASK_SET_CHAR_DECISION_MAKER,
        TASK_SET_PED_DEFENSIVE_AREA,
        TASK_USE_SEQUENCE,
        TASK_SIMPLE_CONTROL_MOVEMENT,
        TASK_MOVE_STAND_STILL,
        TASK_COMPLEX_CONTROL_MOVEMENT,
        TASK_COMPLEX_MOVE_SEQUENCE,
        TASK_MOVE_AROUND_COVERPOINTS,
        TASK_AMBIENT_CLIPS,
        TASK_MOVE_IN_AIR,
        TASK_NETWORK_CLONE,
        TASK_USE_CLIMB_ON_ROUTE,
        TASK_USE_DROPDOWN_ON_ROUTE,
        TASK_USE_LADDER_ON_ROUTE,
        TASK_SET_BLOCKING_OF_NON_TEMPORARY_EVENTS,
        TASK_FORCE_MOTION_STATE,
        TASK_ON_FOOT_SLOPE_SCRAMBLE,

// Climbing tasks
        TASK_GO_TO_AND_CLIMB_LADDER,
        TASK_CLIMB_LADDER_FULLY,
        TASK_RAPPEL,
        TASK_VAULT,
        TASK_DROP_DOWN,

//secondary tasks
        TASK_AFFECT_SECONDARY_BEHAVIOUR,

        TASK_AMBIENT_LOOK_AT_EVENT,

        TASK_OPEN_DOOR,
        TASK_SHOVE_PED,
        TASK_SWAP_WEAPON,
        TASK_GENERAL_SWEEP,

// Service tasks
        TASK_POLICE,
        TASK_POLICE_ORDER_RESPONSE,
        TASK_PURSUE_CRIMINAL,
        TASK_POLICE_GIVE_WARNING,
        TASK_ARREST_PED,
        TASK_ARREST_PED2,
        TASK_BUSTED,
        TASK_FIRE_PATROL,
        TASK_HELI_ORDER_RESPONSE,
        TASK_HELI_PASSENGER_RAPPEL,
        TASK_AMBULANCE_PATROL,
        TASK_POLICE_WANTED_RESPONSE,
        TASK_SWAT,
        TASK_SWAT_LEADER,
        TASK_SWAT_WANTED_RESPONSE,
        TASK_SWAT_ORDER_RESPONSE,
        TASK_SWAT_GO_TO_STAGING_AREA,
        TASK_SWAT_FOLLOW_IN_LINE,
        TASK_WITNESS,
        TASK_GANG_PATROL,
        TASK_ARMY,

//Shocking event reaction tasks
        TASK_SHOCKING_EVENT,
        TASK_SHOCKING_EVENT_WATCH,
        TASK_SHOCKING_EVENT_FLEE,
        TASK_SHOCKING_EVENT_GOTO,
        TASK_SHOCKING_EVENT_HURRYAWAY,
        TASK_SHOCKING_EVENT_REACT_TO_AIRCRAFT,
        TASK_SHOCKING_EVENT_REACT,
        TASK_SHOCKING_EVENT_BACK_AWAY,
        TASK_SHOCKING_POLICE_INVESTIGATE,
        TASK_SHOCKING_EVENT_STOP_AND_STARE,
        TASK_SHOCKING_NICE_CAR_PICTURE,
        TASK_SHOCKING_EVENT_THREAT_RESPONSE,

 // helmet tasks
        TASK_PUT_ON_HELMET,
        TASK_TAKE_OFF_HELMET,

// vehicle tasks
        TASK_CAR_REACT_TO_VEHICLE_COLLISION,
        TASK_REACT_TO_RUNNING_PED_OVER,
        TASK_CAR_REACT_TO_VEHICLE_COLLISION_GET_OUT,

// More dying tasks
        TASK_DEAD,
        TASK_DYING_DEAD,

//scenario tasks
        TASK_DEFER_TO_SCENARIO, // Virual "tasktype" used by the decision maker to decide an event response based on scenario point flags.
        TASK_PARKED_VEHICLE_SCENARIO,
        TASK_WANDERING_SCENARIO,
        TASK_WANDERING_IN_RADIUS_SCENARIO,
        TASK_COMPLEX_DRIVING_SCENARIO,
        TASK_MOVE_BETWEEN_POINTS_SCENARIO,
        TASK_CHAT_SCENARIO,
        //TASK_CONTROL_SCENARIO,
        TASK_COMPLEX_WAIT_FOR_SEAT_TO_BE_FREE,
        TASK_COWER_SCENARIO,
        TASK_DEAD_BODY_SCENARIO,
        TASK_WAIT_FOR_MY_CAR_TO_STOP,
        TASK_COMPLEX_WAIT_FOR_DOOR_TO_BE_OPEN,
        TASK_COMPLEX_DRIVE_WANDER_FOR_TIME,
        TASK_COMPLEX_WAIT_FOR_TIME,
        TASK_COMPLEX_GET_IN_CAR_SCENARIO,
        TASK_MOBILE_PHONE_CHAT_SCENARIO,
        TASK_SAY_AUDIO,
        TASK_COMPLEX_MAKE_MOBILE_CALL,
        TASK_WAIT_FOR_STEPPING_OUT,
        TASK_COUPLE_SCENARIO,
        TASK_USE_SCENARIO,
#if __BANK
        TASK_SCENARIO_ANIM_DEBUG, //Dev only task for debugging animations when using scenarios
#endif //__BANK
        TASK_USE_VEHICLE_SCENARIO,
        TASK_UNALERTED,

//crime tasks
        TASK_STEAL_VEHICLE,
        TASK_REACT_TO_PURSUIT,

//clips (tasks that are sub-classes of CTaskSimpleRunUnloopedClip)
        TASK_RUN_CLIP,
        TASK_RUN_NAMED_CLIP,
        TASK_HIT_WALL,
        TASK_COWER,
        TASK_CROUCH,
        TASK_MELEE,
        TASK_MOVE_MELEE_MOVEMENT,
        TASK_MELEE_ACTION_RESULT,
        TASK_MELEE_UPPERBODY_ANIM,
        TASK_MELEE_UNINTERRUPTABLE,
#if __BANK
        TASK_PREVIEW_MOVE_NETWORK, //Dev only task for previewing a MoVE network on a ped
#endif //__BANK

        TASK_MOVE_SCRIPTED,
        TASK_SCRIPTED_ANIMATION,
        TASK_SYNCHRONIZED_SCENE, // Task for synchronizing an in game animated scene across multiple peds / objects
        TASK_REACH_ARM,          // Performs an ik arm reach to a specified target for a duration

//collision response tasks
        TASK_COMPLEX_EVASIVE_STEP,
        TASK_MOVE_WANDER_AROUND_VEHICLE,
        TASK_WALK_ROUND_FIRE,
        TASK_COMPLEX_STUCK_IN_AIR,
        TASK_WALK_ROUND_ENTITY,
        TASK_MOVE_WALK_ROUND_VEHICLE,
        TASK_MOVE_WALK_ROUND_VEHICLE_DOOR,

//threat response tasks
        TASK_REACT_TO_GUN_AIMED_AT,
        TASK_COMPLEX_EXTINGUISH_FIRES,
        TASK_ON_FOOT_DUCK_AND_COVER,

//car tasks

//public car tasks
        TASK_AGGRESSIVE_RUBBERNECK,
        TASK_COMPLEX_LEAVE_CAR_AND_FLEE,
        TASK_COMPLEX_SCREAM_IN_CAR_THEN_LEAVE,
        TASK_IN_VEHICLE_BASIC,
        TASK_CAR_DRIVE_WANDER,
        TASK_LEAVE_ANY_CAR,
        TASK_COMPLEX_GET_OFF_BOAT,
        TASK_CAR_DRIVE_POINT_ROUTE,
        TASK_CAR_SET_TEMP_ACTION,
        TASK_BRING_VEHICLE_TO_HALT,
        TASK_CAR_DRIVE,
        TASK_COMPLEX_CAR_DRIVE_MISSION_KILL_PED,
        TASK_PLAYER_DRIVE,
        TASK_ENTER_VEHICLE,
        TASK_ENTER_VEHICLE_ALIGN,
        TASK_OPEN_VEHICLE_DOOR_FROM_OUTSIDE,
        TASK_ENTER_VEHICLE_SEAT,
        TASK_CLOSE_VEHICLE_DOOR_FROM_INSIDE,
        TASK_IN_VEHICLE_SEAT_SHUFFLE,
        TASK_OPEN_VEHICLE_DOOR_FROM_INSIDE,
        TASK_EXIT_VEHICLE_SEAT,
        TASK_CLOSE_VEHICLE_DOOR_FROM_OUTSIDE,
        TASK_CONTROL_VEHICLE,
        TASK_MOTION_IN_AUTOMOBILE,
        TASK_MOTION_ON_BICYCLE,
        TASK_MOTION_ON_BICYCLE_CONTROLLER,
        TASK_MOTION_IN_VEHICLE,
        TASK_MOTION_IN_TURRET,
        TASK_REACT_TO_BEING_JACKED,
        TASK_REACT_TO_BEING_ASKED_TO_LEAVE_VEHICLE,
        TASK_TRY_TO_GRAB_VEHICLE_DOOR,
        TASK_GET_ON_TRAIN,
        TASK_GET_OFF_TRAIN,
        TASK_RIDE_TRAIN,
#if __BANK
        TASK_ATTACHED_VEHICLE_ANIM_DEBUG,
#endif // __BANK

//horse related tasks
        TASK_MOTION_RIDE_HORSE,
        TASK_MOVE_MOUNTED,
        TASK_MOVE_MOUNTED_SPUR_CONTROL,
        TASK_MOUNT_ANIMAL,
        TASK_DISMOUNT_ANIMAL,
        TASK_MOUNT_SEAT,
        TASK_GETTING_MOUNTED,
        TASK_DISMOUNT_SEAT,
        TASK_GETTING_DISMOUNTED,
        TASK_MOUNT_THROW_PROJECTILE,
        TASK_RIDER_REARUP,
        TASK_JUMP_MOUNTED,
        TASK_MOVE_DRAFT_ANIMAL,
        TASK_MOUNT_FOLLOW_NEAREST_ROAD,

//private car tasks (used only by public car tasks)
        TASK_GO_TO_CAR_DOOR_AND_STAND_STILL,
        TASK_MOVE_GO_TO_VEHICLE_DOOR,
        TASK_SET_PED_IN_VEHICLE,
        TASK_SET_PED_OUT_OF_VEHICLE,
        TASK_VEHICLE_MOUNTED_WEAPON,
        TASK_VEHICLE_GUN,
        TASK_VEHICLE_PROJECTILE,
        TASK_START_CAR,
        TASK_VEHICLE_SHUNT,
        TASK_SMASH_CAR_WINDOW,

//goto tasks
        TASK_MOVE_GO_TO_POINT,
        TASK_MOVE_ACHIEVE_HEADING,
        TASK_MOVE_FACE_TARGET,
        TASK_MOVE_GO_TO_POINT_AND_STAND_STILL,
        TASK_MOVE_FOLLOW_POINT_ROUTE,
        TASK_MOVE_SEEK_ENTITY_STANDARD,
        TASK_MOVE_SEEK_ENTITY_LAST_NAV_MESH_INTERSECTION,
        TASK_MOVE_SEEK_ENTITY_OFFSET_ROTATE,
        TASK_MOVE_SEEK_ENTITY_OFFSET_FIXED,
        TASK_MOVE_SEEK_ENTITY_RADIUS_ANGLE,
        TASK_EXHAUSTED_FLEE,
        TASK_GROWL_AND_FLEE,
        TASK_SCENARIO_FLEE,
        TASK_SMART_FLEE,
        TASK_FLY_AWAY,
        TASK_WALK_AWAY,
        TASK_WANDER,
        TASK_WANDER_IN_AREA,
        TASK_FOLLOW_LEADER_IN_FORMATION,
        TASK_GO_TO_POINT_ANY_MEANS,
        TASK_COMPLEX_TURN_TO_FACE_ENTITY,
        TASK_FOLLOW_LEADER_ANY_MEANS,
        TASK_PLAYER_HORSE_FOLLOW,
        TASK_FLY_TO_POINT,
        TASK_FLYING_WANDER,
        TASK_GO_TO_POINT_AIMING,
        TASK_GO_TO_SCENARIO,
        TASK_FOLLOW_PATROL_ROUTE,
        TASK_SEEK_ENTITY_AIMING,
        TASK_SLIDE_TO_COORD,
        TASK_SWIMMING_WANDER,
        TASK_COMPLEX_AVOID_ENTITY,
        TASK_MOVE_TRACKING_ENTITY,
        TASK_MOVE_FOLLOW_NAVMESH,
        TASK_MOVE_GO_TO_POINT_ON_ROUTE,
        TASK_ESCAPE_BLAST,
        TASK_MOVE_WANDER,
        TASK_MOVE_BE_IN_FORMATION,
        TASK_MOVE_CROWD_AROUND_LOCATION,
        TASK_MOVE_CROSS_ROAD_AT_TRAFFIC_LIGHTS,
        TASK_MOVE_WAIT_FOR_TRAFFIC,
        TASK_MOVE_GOTO_POINT_STAND_STILL_ACHIEVE_HEADING,
        TASK_MOVE_WAIT_FOR_NAVMESH_SPECIAL_ACTION_EVENT,
        TASK_MOVE_GOTO_SAFE_POSITION_ON_NAVMESH,
        TASK_MOVE_RETURN_TO_ROUTE,
        TASK_MOVE_GOTO_SHELTER_AND_WAIT,
        TASK_MOVE_GET_ONTO_MAIN_NAVMESH,
        TASK_MOVE_SLIDE_TO_COORD,
        TASK_MOVE_GOTO_POINT_RELATIVE_TO_ENTITY_AND_STAND_STILL,
        TASK_HELICOPTER_STRAFE,
        TASK_COMPLEX_USE_MOBILE_PHONE_AND_MOVEMENT,
        TASK_GET_OUT_OF_WATER,
        TASK_COMPLEX_SEARCH_WANDER_AFTER_TIME,
        TASK_COMPLEX_MOVE_FOLLOW_NAV_NODES_ROUTE,
        TASK_MOVE_FOLLOW_ENTITY_OFFSET,
        TASK_TEST_CLIP_DISTANCE,
        TASK_FOLLOW_WAYPOINT_RECORDING,
        TASK_DROP_OVER_EDGE,
        TASK_GENERIC_MOVE_TO_POINT,

        // Motion task tree tasks

        // Entity base tasks
        TASK_MOTION_PED,
        TASK_MOTION_PED_LOW_LOD,
        TASK_MOTION_ANIMAL,

        // Motion tasks
        TASK_MOTION_BASIC_LOCOMOTION,
        TASK_HUMAN_LOCOMOTION,
        TASK_MOTION_BASIC_LOCOMOTION_LOW_LOD,
        TASK_MOTION_STRAFING,
        TASK_MOTION_TENNIS,
        TASK_MOTION_AIMING,
        TASK_ON_FOOT_BIRD,
        TASK_ON_FOOT_FLIGHTLESS_BIRD,
        TASK_ON_FOOT_HORSE,

        TASK_ON_FOOT_DOG,
        TASK_ON_FOOT_DEER,
        TASK_ON_FOOT_FISH,
        TASK_ON_FOOT_QUAD,
        TASK_MOTION_DIVING,
        TASK_MOTION_SWIMMING,
        TASK_MOTION_PARACHUTING,
        TASK_MOTION_DRUNK,
        TASK_REPOSITION_MOVE,
        TASK_MOTION_AIMING_TRANSITION,

//fight tasks
        // new weapon/fight tasks
        TASK_THROW_PROJECTILE,

        TASK_COVER,
        TASK_MOTION_IN_COVER,
        TASK_AIM_AND_THROW_PROJECTILE,
        TASK_GUN,
        TASK_AIM_FROM_GROUND,
        TASK_AIM_GUN_STRAFE,
        TASK_AIM_GUN_CLIMBING,
        TASK_AIM_GUN_CLIMBING_LEDGE,
        TASK_AIM_GUN_VEHICLE_DRIVE_BY,
        TASK_AIM_GUN_SCRIPTED,
        TASK_AIM_GUN_RUN_AND_GUN,
        TASK_RELOAD_GUN,
        TASK_WEAPON_BLOCKED,
        TASK_ENTER_COVER,
        TASK_EXIT_COVER,
        TASK_AIM_GUN_FROM_COVER_INTRO,
        TASK_AIM_GUN_FROM_COVER_OUTRO,
        TASK_AIM_GUN_BLIND_FIRE,
        TASK_AIM_GUN_BLIND_FIRE_INTRO,
        TASK_AIM_GUN_BLIND_FIRE_OUTRO,
        TASK_COMBAT_CLOSEST_TARGET_IN_AREA,
        TASK_ADDITIONAL_COMBAT_TASK,
        TASK_IN_COVER,
        TASK_VEHICLE_DRIVE_BY,
        TASK_AIM_GUN_STANDING,
        TASK_AIM_GUN_ON_FOOT_PM,
        TASK_AIM_SWEEP,
        TASK_ARREST,
        TASK_CUFFED,
        TASK_IN_CUSTODY,
        TASK_INCAPACITATED,
        TASK_PLAY_CUFFED_SECONDARY_ANIMS,

//Animal combat tasks
        TASK_SHARK_CIRCLE,
        TASK_SHARK_ATTACK,

//gang/partner tasks
        TASK_AGITATED,
        TASK_AGITATED_ACTION,
        TASK_CONFRONT,
        TASK_INTIMIDATE,
        TASK_SHOVE,
        TASK_SHOVED,

//misc
        TASK_FINISHED,
        TASK_CROUCH_TOGGLE,
        TASK_REVIVE,
        TASK_CLONED_FSM_TEST_HARNESS,

// phone / goggles tasks
        TASK_COMPLEX_USE_MOBILE_PHONE,
        TASK_SIMPLE_PHONE_TALK,
        TASK_SIMPLE_PHONE_IN,
        TASK_SIMPLE_PHONE_OUT,

// parachute tasks
        TASK_PARACHUTE,
        TASK_PARACHUTE_OBJECT,

// ped variation tasks
        TASK_TAKE_OFF_PED_VARIATION,

// jetpack tasks.
        TASK_JETPACK,
        TASK_MOTION_JETPACK,

// Combat tasks
        TASK_COMBAT_SEEK_COVER,
        TASK_COMBAT_CHARGE,
        TASK_COMBAT_FLANK,
        TASK_COMBAT,
        TASK_COMBAT_MOUNTED,
        TASK_MOVE_CIRCLE,
        TASK_MOVE_COMBAT_MOUNTED,
        TASK_SEARCH,
        TASK_SEARCH_ON_FOOT,
        TASK_SEARCH_IN_AUTOMOBILE,
        TASK_SEARCH_IN_BOAT,
        TASK_SEARCH_IN_HELI,
        TASK_THREAT_RESPONSE,
        TASK_INVESTIGATE,
        TASK_STAND_GUARD_FSM,
        TASK_PATROL,
        TASK_SHOOT_AT_TARGET,
        TASK_SET_AND_GUARD_AREA,
        TASK_STAND_GUARD,
        TASK_SEPARATE,
        TASK_STAY_IN_COVER,
        TASK_VEHICLE_COMBAT,
        TASK_VEHICLE_PERSUIT,
        TASK_VEHICLE_CHASE,
        TASK_DRAGGING_TO_SAFETY,
        TASK_DRAGGED_TO_SAFETY,
        TASK_VARIED_AIM_POSE,
        TASK_MOVE_WITHIN_ATTACK_WINDOW,
        TASK_MOVE_WITHIN_DEFENSIVE_AREA,
        TASK_SHOOT_OUT_TIRE,
        TASK_SHELL_SHOCKED,
        TASK_BOAT_CHASE,
        TASK_BOAT_COMBAT,
        TASK_BOAT_STRAFE,
        TASK_HELI_CHASE,
        TASK_HELI_COMBAT,
        TASK_SUBMARINE_COMBAT,
        TASK_SUBMARINE_CHASE,
        TASK_PLANE_CHASE,
        TASK_TARGET_UNREACHABLE,
        TASK_TARGET_UNREACHABLE_IN_INTERIOR,
        TASK_TARGET_UNREACHABLE_IN_EXTERIOR,
        TASK_STEALTH_KILL,
        TASK_WRITHE,
        TASK_ADVANCE,
        TASK_CHARGE,
        TASK_MOVE_TO_TACTICAL_POINT,
        TASK_TO_HURT_TRANSIT,
        TASK_ANIMATED_HIT_BY_EXPLOSION,

// Ragdoll tasks
        TASK_NM_RELAX, // Don't add ragdoll tasks before this
        TASK_NM_ROLL_UP_AND_RELAX,
        TASK_NM_POSE,
        TASK_NM_BRACE,
        TASK_NM_BUOYANCY,
        TASK_NM_INJURED_ON_GROUND,
        TASK_NM_SHOT,
        TASK_NM_HIGH_FALL,
        TASK_NM_BALANCE,
        TASK_NM_ELECTROCUTE,
        TASK_NM_PROTOTYPE,
        TASK_NM_EXPLOSION,
        TASK_NM_ONFIRE,
        TASK_NM_SCRIPT_CONTROL,
        TASK_NM_JUMP_ROLL_FROM_ROAD_VEHICLE,
        TASK_NM_FLINCH,
        TASK_NM_SIT,
        TASK_NM_FALL_DOWN,

        TASK_BLEND_FROM_NM,
        TASK_NM_CONTROL,
        TASK_NM_DANGLE,
        TASK_NM_SLUNG_OVER_SHOULDER,

#if __DEV
        TASK_NM_BIND_POSE,
#endif  // __DEV
        TASK_NM_SHOOTING_WHILE_ATTACHED,
        TASK_NM_GENERIC_ATTACH,
        TASK_NM_DRUNK,
        //TASK_NM_STUMBLE,

        TASK_NM_DRAGGING_TO_SAFETY,

        TASK_NM_THROUGH_WINDSCREEN,

        TASK_NM_RIVER_RAPIDS,

        TASK_NM_SIMPLE,

        TASK_RAGE_RAGDOLL,

        TASK_RAGDOLL_LAST, // Don't add ragdoll tasks after this

//project specific tasks
        TASK_MOVE_SKI_BASE,

        TASK_JUMPVAULT,
        TASK_JUMP,
        TASK_FALL,

        TASK_JUMP_IN_AIR,
        TASK_REACT_AIM_WEAPON,
        TASK_CHAT,
        TASK_MOBILE_PHONE,
        TASK_REACT_TO_DEAD_PED,
        TASK_WATCH_INVESTIGATION,
        TASK_SEARCH_FOR_UNKNOWN_THREAT,
        TASK_CHECK_PED_IS_DEAD,
        TASK_BOMB,
        TASK_DETONATOR,
        TASK_SHOOTING_WHILE_ATTACHED,
        TASK_ANIMATED_ATTACH,
#if __DEV
        TASK_BIND_POSE,
#endif  // __DEV
        TASK_ELECTROCUTE,
        TASK_GO_TO_POINT_USING_COVER,
        TASK_MOVE_IN_FORMATION,
        TASK_FOLLOW_LEADER_IN_PAIR,
        TASK_PLAY_CLIP_AND_SLIDE_TO_POSITION,
        TASK_CUTSCENE,
        TASK_REACT_TO_EXPLOSION,
        TASK_REACT_TO_IMMINENT_EXPLOSION,
        TASK_DIVE_TO_GROUND,
        TASK_REACT_AND_FLEE,
        TASK_SIDESTEP,
        TASK_CALL_POLICE,
        TASK_REACT_IN_DIRECTION,
        TASK_REACT_TO_BUDDY_SHOT,
        TASK_FRIENDLY_FIRE_NEAR_MISS,
        TASK_FRIENDLY_AIMED_AT,
        TASK_PLAYER_DEATH_REACT,

        //real vehicle AI tasks
        TASK_VEHICLE_FIRST_TASK,
        TASK_VEHICLE_GOTO = TASK_VEHICLE_FIRST_TASK,
        TASK_VEHICLE_GOTO_AUTOMOBILE_NEW,
        TASK_VEHICLE_GOTO_PLANE,
        TASK_VEHICLE_GOTO_HELICOPTER,
        TASK_VEHICLE_GOTO_SUBMARINE,
        TASK_VEHICLE_GOTO_BOAT,
        //TASK_VEHICLE_GOTO_RACING,
        TASK_VEHICLE_GOTO_POINT_AUTOMOBILE,
        TASK_VEHICLE_GOTO_POINT_WITH_AVOIDANCE_AUTOMOBILE,
        TASK_VEHICLE_PURSUE,
        TASK_VEHICLE_RAM,
        TASK_VEHICLE_SPIN_OUT,
        TASK_VEHICLE_APPROACH,
        TASK_VEHICLE_THREE_POINT_TURN,
        TASK_VEHICLE_DEAD_DRIVER,
        TASK_VEHICLE_CRUISE_NEW,
        TASK_VEHICLE_CRUISE_BOAT,
        TASK_VEHICLE_STOP,
        TASK_VEHICLE_PULL_OVER,
        TASK_VEHICLE_PASSENGER_EXIT,
        TASK_VEHICLE_FLEE,
        TASK_VEHICLE_FLEE_AIRBORNE,
        TASK_VEHICLE_FLEE_BOAT,
        TASK_VEHICLE_FOLLOW_RECORDING,
        TASK_VEHICLE_FOLLOW,
        TASK_VEHICLE_BLOCK,
        TASK_VEHICLE_BLOCK_CRUISE_IN_FRONT,
        TASK_VEHICLE_BLOCK_BRAKE_IN_FRONT,
        TASK_VEHICLE_BLOCK_BACK_AND_FORTH,
        TASK_VEHICLE_CRASH,
        TASK_VEHICLE_LAND,
        TASK_VEHICLE_LAND_PLANE,
        TASK_VEHICLE_HOVER,
        TASK_VEHICLE_ATTACK,
        TASK_VEHICLE_ATTACK_TANK,
        TASK_VEHICLE_CIRCLE,
        TASK_VEHICLE_POLICE_BEHAVIOUR,
        TASK_VEHICLE_POLICE_BEHAVIOUR_HELICOPTER,
        TASK_VEHICLE_POLICE_BEHAVIOUR_BOAT,
        TASK_VEHICLE_ESCORT,
        TASK_VEHICLE_HELI_PROTECT,
        TASK_VEHICLE_PLAYER_DRIVE,
        TASK_VEHICLE_PLAYER_DRIVE_AUTOMOBILE,
        TASK_VEHICLE_PLAYER_DRIVE_BIKE,
        TASK_VEHICLE_PLAYER_DRIVE_BOAT,
        TASK_VEHICLE_PLAYER_DRIVE_SUBMARINE,
        TASK_VEHICLE_PLAYER_DRIVE_SUBMARINECAR,
        TASK_VEHICLE_PLAYER_DRIVE_AMPHIBIOUS_AUTOMOBILE,
        TASK_VEHICLE_PLAYER_DRIVE_PLANE,
        TASK_VEHICLE_PLAYER_DRIVE_HELI,
        TASK_VEHICLE_PLAYER_DRIVE_AUTOGYRO,
        TASK_VEHICLE_PLAYER_DRIVE_DIGGER_ARM,
        TASK_VEHICLE_PLAYER_DRIVE_TRAIN,
        TASK_VEHICLE_PLANE_CHASE,
        TASK_VEHICLE_NO_DRIVER,
        TASK_VEHICLE_ANIMATION,
        TASK_VEHICLE_CONVERTIBLE_ROOF,
        TASK_VEHICLE_PARK_NEW,
        TASK_VEHICLE_FOLLOW_WAYPOINT_RECORDING,
        TASK_VEHICLE_GOTO_NAVMESH,
        TASK_VEHICLE_REACT_TO_COP_SIREN,
        TASK_VEHICLE_GOTO_LONGRANGE,
//temp action vehicle AI tasks
        TASK_VEHICLE_WAIT,
        TASK_VEHICLE_REVERSE,
        TASK_VEHICLE_BRAKE,
        TASK_VEHICLE_HANDBRAKE,
        TASK_VEHICLE_TURN,
        TASK_VEHICLE_GO_FORWARD,
        TASK_VEHICLE_SWERVE,
        TASK_VEHICLE_FLY_DIRECTION,
        TASK_VEHICLE_HEADON_COLLISION,
        TASK_VEHICLE_BOOST_USE_STEERING_ANGLE,
        TASK_VEHICLE_SHOT_TIRE,
        TASK_VEHICLE_BURNOUT,
        TASK_VEHICLE_REV_ENGINE,
        TASK_VEHICLE_SURFACE_IN_SUBMARINE,
        TASK_VEHICLE_PULL_ALONGSIDE,
        TASK_VEHICLE_TRANSFORM_TO_SUBMARINE,
        TASK_ANIMATED_FALLBACK,
// The end
        MAX_NUM_TASK_TYPES
    };

    // Helper function
    bool IsRagdollTask(int taskType);
    bool IsCombatTask(int taskType);
    bool IsPlayerDriveTask(int taskType);
};

// "Task type enums out of sync with commands_task.sch" if this assert fires
CompileTimeAssert(CTaskTypes::TASK_HANDS_UP == 0);
CompileTimeAssert(CTaskTypes::TASK_CLIMB_LADDER == 1);

#endif // TASK_TYPES_H
